image:
  - Visual Studio 2019
  - Ubuntu
  - Ubuntu2004
  - macOS

environment:
  Codecov_Token:
    secure: BO0sdRpYxw4dTKVnhXbaiY1VCLxIgdDM4mlQBgVhr0+z4QtYgMfK8O3o+YSKNP8+

before_build:
  - nuget restore

build:
  project: Hashicon.sln
  verbosity: minimal

test_script:
  - dotnet test /p:AltCover=true /p:AltCoverXmlreport="../Coverage_Result.xml" /p:AltCoverAssemblyFilter="XUnit" /p:AltCoverAssemblyFilter="^(?!(Hashicon)).*$" /p:AltCoverAssemblyExcludeFilter="Hashicon.Test"
  - sh: curl -s https://codecov.io/bash | bash -t $Codecov_Token -f ./Coverage_Result.xml