image:
  - Visual Studio 2019
  - Ubuntu
  - Ubuntu2004
  - macOS

environment:
  Codecov_Token:
    secure: 4mR2JJpg4jer0+mhpQqDMnJ+QejHqin4LQAxnIxF5FKtrFj2SDMNNefYhySt0Saj

before_build:
  - nuget restore

build:
  project: Hashicon.sln
  verbosity: minimal

test_script:
  - dotnet test /p:AltCover=true /p:AltCoverXmlreport="../Coverage_Result.xml" /p:AltCoverAssemblyFilter="XUnit" /p:AltCoverAssemblyFilter="^(?!(Hashicon)).*$" /p:AltCoverAssemblyExcludeFilter="Hashicon.Test"
  - ps: |-
    if (!($isLinux)) {
      Exit-AppveyorBuild
    }
  - sh: |-
    if grep -Fxq 20.04 /etc/issue; then
      bash <(curl -s https://codecov.io/bash) -t $Codecov_Token -f ./Coverage_Result.xml
    fi
